version: '2'

services:
    aplicaciones:
        image: tianon/true
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony


    db:
        image: mysql
        volumes:
            - ${MYSQL_LOCAL_STORAGE}:/var/lib/mysql
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}


    redis:
        build: redis
        ports:
            - ${REDIS_PORT}:6379


    #elasticsearch:
    #    image: elasticsearch
    #    ports:
    #        - 9200:9200
    #        - 9300:9300
    elk:
        image: willdurand/elk
        ports:
            - ${ELK_PORT}:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx


    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes_from:
            - aplicaciones
            # MAC USERS
            #- lsyncd

    ###
    ### MAC USERS
    #lsyncd:
    #    image: dracoblue/lsyncd
    #    environment:
    #        - SOURCES=/vendor
    #        - DESTINATIONS=/var/www/symfony/vendor
    #        - EXCLUDES=.svn:.git:.docker
    #    volumes:
    #        - /home/alejandro/mascoteros/mascoteros/:/var/www/symfony:cached
    #        - ./vendor:/vendor
    #        - /var/www/symfony/vendor


    nginx:
        build: nginx
        ports:
            - ${NGINX_PORT}:80
        volumes_from:
            - aplicaciones
        volumes:
            - ${LOGS_PATH}/nginx/:/var/log/nginx


volumes:
    mysql:
        driver: "local"
    redis:
        driver: "local"